#ifndef MYBB_EXAMPLE_H
#define MYBB_EXAMPLE_H

/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

/*
 * Example function
 */
extern void LibHelloWorld(void);

#endif /* MYBB_EXAMPLE_H */
